apiVersion: apps/v1
kind: Deployment
metadata:
  name: vprocache
  labels:
    app: vprocache
spec:
  selector:
    matchLabels:
      app: vprocache
  replicas: 1
  template:
    metadata:
      labels:
        app: vprocache
    spec:
      containers:
        - name: vprocache
          image: memcached
          ports:
            - name: vprocache-port
              containerPort: 11211
---
apiVersion: v1
kind: Service
metadata:
  name: vprocache01
spec:
  ports:
    - port: 11211
      targetPort: vprocache-port
      protocol: TCP
  selector:
    app: vprocache
  type: ClusterIP

